In [1]:
import pip
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score,roc_auc_score

In [2]:
import pandas as pd
import numpy as np
import pandas.testing as tm
import matplotlib.pyplot as plt

In [48]:
data=pd.read_csv(r'C:\Users\Student\Downloads\visit2_TotalOutcome (2)(2).csv')

In [49]:
np.random.seed(1024)

In [51]:
y=data.CLASS
x=data.drop("CLASS", axis = 1)
z=x.drop("MOVE", axis = 1)
a=z.drop("LIPA08", axis = 1)
b=a.drop("CHMA09", axis = 1)
c=b.drop("HMTA03", axis = 1)
ccols = c.columns

In [52]:
import impyute as impy
imputed_c=impy.median(c.values)

In [53]:
 imputed_c

array([[1.00000000e+00, 2.91271562e+01, 0.00000000e+00, ...,
        3.00000000e+00, 1.59000000e+02, 1.00000000e+00],
       [2.00000000e+00, 3.43072305e+01, 0.00000000e+00, ...,
        2.00000000e+00, 1.64000000e+02, 0.00000000e+00],
       [3.00000000e+00, 3.29552215e+01, 5.66000000e+01, ...,
        2.00000000e+00, 1.64000000e+02, 0.00000000e+00],
       ...,
       [1.57860000e+04, 3.06425574e+01, 0.00000000e+00, ...,
        3.00000000e+00, 1.79000000e+02, 0.00000000e+00],
       [1.57870000e+04, 3.69973173e+01, 0.00000000e+00, ...,
        1.00000000e+00, 1.67000000e+02, 0.00000000e+00],
       [1.57890000e+04, 3.39803904e+01, 7.99700000e+02, ...,
        3.00000000e+00, 1.66000000e+02, 0.00000000e+00]])

In [54]:
imputed_c = pd.DataFrame(imputed_c,columns=ccols)

In [55]:
imputed_c

,ID_C,BMI21,ETHANL24,CIGT21,CURSMK21,CARB,CHOL,DFIB,PROT,SFAT,...,HYPRT24,CIGTYR01,V2AG22,RACGRP,DIABTS22,LVL01,GENDER,CIGT21.1,ANTA01,CHOLMDCCODE21
0,1.0,29.127156,0.0,3.0,0.0,178.745714,201.31,15.405,65.235000,17.805,...,0.0,0.0,63.0,0.0,0.0,3.0,1.0,3.0,159.0,1.0
1,2.0,34.307231,0.0,2.0,0.0,178.745714,201.31,15.405,65.235000,17.805,...,0.0,0.0,48.0,1.0,0.0,5.0,1.0,2.0,164.0,0.0
2,3.0,32.955221,56.6,2.0,0.0,178.745714,201.31,15.405,65.235000,17.805,...,0.0,315.0,50.0,0.0,0.0,4.0,1.0,2.0,164.0,0.0
3,4.0,22.038567,0.0,3.0,0.0,178.745714,201.31,15.405,65.235000,17.805,...,0.0,0.0,50.0,0.0,0.0,5.0,1.0,3.0,165.0,0.0
4,5.0,31.650009,108.0,2.0,0.0,182.821429,128.89,23.800,60.075714,9.400,...,0.0,225.0,59.0,0.0,0.0,6.0,1.0,2.0,163.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13621,15784.0,45.714286,47.5,3.0,0.0,178.745714,201.31,15.405,65.235000,17.805,...,0.0,0.0,67.0,0.0,0.0,5.0,0.0,3.0,175.0,0.0
13622,15785.0,26.259585,177.4,1.0,1.0,178.745714,201.31,15.405,65.235000,17.805,...,0.0,390.0,60.0,0.0,0.0,2.0,0.0,1.0,169.0,0.0
13623,15786.0,30.642557,0.0,3.0,0.0,178.745714,201.31,15.405,65.235000,17.805,...,0.0,0.0,49.0,0.0,0.0,4.0,0.0,3.0,179.0,0.0
13624,15787.0,36.997317,0.0,1.0,1.0,178.745714,201.31,15.405,65.235000,17.805,...,0.0,0.0,51.0,1.0,1.0,5.0,1.0,1.0,167.0,0.0
13625,15789.0,33.980390,799.7,3.0,0.0,178.745714,201.31,15.405,65.235000,17.805,...,0.0,0.0,48.0,1.0,1.0,2.0,0.0,3.0,166.0,0.0

In [56]:
imputed_c.isna().sum()

ID_C              0
BMI21             0
ETHANL24          0
CIGT21            0
CURSMK21          0
CARB              0
CHOL              0
DFIB              0
PROT              0
SFAT              0
TFAT              0
TCAL              0
HDLSIU21          0
LDLSIU22          0
TCHSIU21          0
TRGSIU21          0
SBPB15            0
SBPB16            0
ANTB04A           0
ANTB04B           0
CGMI24            0
APASIU21          0
APBSIU21          0
HYPTMD21          0
ANTICOAGCODE21    0
ASPIRINCODE21     0
STATINCODE21      0
HYPTMDC#N/AD21    0
HYPRT24           0
CIGTYR01          0
V2AG22            0
RACGRP            0
DIABTS22          0
LVL01             0
GENDER            0
CIGT21.1          0
ANTA01            0
CHOLMDCCODE21     0
dtype: int64

In [57]:
c_train, c_test, y_train, y_test = train_test_split(imputed_c,y,test_size = 0.2)
ccols = c_train.columns
csols = c_test.columns

In [58]:
m1 = c_train.dtypes
m2 = c_test.dtypes

In [59]:
m1

ID_C              float64
BMI21             float64
ETHANL24          float64
CIGT21            float64
CURSMK21          float64
CARB              float64
CHOL              float64
DFIB              float64
PROT              float64
SFAT              float64
TFAT              float64
TCAL              float64
HDLSIU21          float64
LDLSIU22          float64
TCHSIU21          float64
TRGSIU21          float64
SBPB15            float64
SBPB16            float64
ANTB04A           float64
ANTB04B           float64
CGMI24            float64
APASIU21          float64
APBSIU21          float64
HYPTMD21          float64
ANTICOAGCODE21    float64
ASPIRINCODE21     float64
STATINCODE21      float64
HYPTMDC#N/AD21    float64
HYPRT24           float64
CIGTYR01          float64
V2AG22            float64
RACGRP            float64
DIABTS22          float64
LVL01             float64
GENDER            float64
CIGT21.1          float64
ANTA01            float64
CHOLMDCCODE21     float64
dtype: object

In [60]:
m2

ID_C              float64
BMI21             float64
ETHANL24          float64
CIGT21            float64
CURSMK21          float64
CARB              float64
CHOL              float64
DFIB              float64
PROT              float64
SFAT              float64
TFAT              float64
TCAL              float64
HDLSIU21          float64
LDLSIU22          float64
TCHSIU21          float64
TRGSIU21          float64
SBPB15            float64
SBPB16            float64
ANTB04A           float64
ANTB04B           float64
CGMI24            float64
APASIU21          float64
APBSIU21          float64
HYPTMD21          float64
ANTICOAGCODE21    float64
ASPIRINCODE21     float64
STATINCODE21      float64
HYPTMDC#N/AD21    float64
HYPRT24           float64
CIGTYR01          float64
V2AG22            float64
RACGRP            float64
DIABTS22          float64
LVL01             float64
GENDER            float64
CIGT21.1          float64
ANTA01            float64
CHOLMDCCODE21     float64
dtype: object

In [37]:
cpols=c_train.columns
csols=c_test.columns
c_train = pd.DataFrame(c_train,columns=ccols)

In [61]:
c_train

,ID_C,BMI21,ETHANL24,CIGT21,CURSMK21,CARB,CHOL,DFIB,PROT,SFAT,...,HYPRT24,CIGTYR01,V2AG22,RACGRP,DIABTS22,LVL01,GENDER,CIGT21.1,ANTA01,CHOLMDCCODE21
3690,4300.0,47.992370,0.0,2.0,0.0,178.745714,201.31,15.405,65.235,17.805,...,1.0,400.0,49.0,0.0,1.0,4.0,0.0,2.0,173.0,0.0
10828,12526.0,18.476762,0.0,3.0,0.0,178.745714,201.31,15.405,65.235,17.805,...,0.0,0.0,58.0,0.0,0.0,4.0,1.0,3.0,163.0,0.0
6959,8098.0,34.102680,151.0,2.0,0.0,178.745714,201.31,15.405,65.235,17.805,...,1.0,315.0,65.0,0.0,0.0,5.0,0.0,2.0,189.0,0.0
1182,1392.0,28.704297,0.0,1.0,1.0,178.745714,201.31,15.405,65.235,17.805,...,0.0,2880.0,65.0,1.0,0.0,1.0,0.0,1.0,173.0,0.0
1958,2285.0,20.848519,0.0,3.0,0.0,296.410000,322.50,31.940,81.180,37.180,...,1.0,0.0,68.0,0.0,0.0,1.0,0.0,3.0,169.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
601,702.0,28.727377,105.6,2.0,0.0,178.745714,201.31,15.405,65.235,17.805,...,0.0,620.0,59.0,0.0,0.0,3.0,0.0,2.0,177.0,0.0
2661,3100.0,26.723838,0.0,2.0,0.0,178.745714,201.31,15.405,65.235,17.805,...,1.0,960.0,53.0,0.0,0.0,3.0,0.0,2.0,174.0,1.0
2540,2959.0,20.918528,10.8,2.0,0.0,178.745714,201.31,15.405,65.235,17.805,...,0.0,100.0,49.0,0.0,0.0,5.0,1.0,2.0,170.0,0.0
9105,10563.0,32.596755,0.0,2.0,0.0,178.745714,201.31,15.405,65.235,17.805,...,1.0,120.0,51.0,0.0,0.0,5.0,1.0,2.0,167.0,0.0
6075,7071.0,36.784597,211.4,2.0,0.0,178.745714,201.31,15.405,65.235,17.805,...,0.0,880.0,65.0,0.0,0.0,4.0,1.0,2.0,166.0,0.0

In [63]:
c_test = pd.DataFrame(c_test,columns=csols)

In [64]:
c_test

,ID_C,BMI21,ETHANL24,CIGT21,CURSMK21,CARB,CHOL,DFIB,PROT,SFAT,...,HYPRT24,CIGTYR01,V2AG22,RACGRP,DIABTS22,LVL01,GENDER,CIGT21.1,ANTA01,CHOLMDCCODE21
5439,6344.0,22.021815,39.6,2.0,0.0,178.745714,201.31,15.405,65.235,17.805,...,1.0,270.0,58.0,0.0,1.0,3.0,0.0,2.0,173.0,0.0
4298,5010.0,35.037379,0.0,2.0,0.0,178.745714,201.31,15.405,65.235,17.805,...,1.0,0.0,66.0,1.0,0.0,2.0,1.0,2.0,157.0,0.0
2711,3158.0,33.558239,0.0,3.0,0.0,178.745714,201.31,15.405,65.235,17.805,...,0.0,0.0,54.0,0.0,0.0,5.0,1.0,3.0,160.0,0.0
7881,9154.0,37.160301,422.4,1.0,1.0,178.745714,201.31,15.405,65.235,17.805,...,0.0,108.0,48.0,1.0,0.0,6.0,1.0,1.0,167.0,0.0
93,106.0,31.072443,10.8,3.0,0.0,178.745714,201.31,15.405,65.235,17.805,...,0.0,0.0,51.0,0.0,0.0,4.0,1.0,3.0,160.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,1191.0,23.161750,0.0,2.0,0.0,178.745714,201.31,15.405,65.235,17.805,...,0.0,525.0,63.0,0.0,0.0,3.0,1.0,2.0,171.0,0.0
7552,8766.0,27.458256,223.2,1.0,1.0,178.745714,201.31,15.405,65.235,17.805,...,0.0,640.0,47.0,1.0,0.0,2.0,0.0,1.0,175.0,0.0
11449,13265.0,27.681661,407.0,2.0,0.0,178.745714,201.31,15.405,65.235,17.805,...,0.0,620.0,59.0,0.0,0.0,5.0,0.0,2.0,170.0,0.0
3702,4313.0,24.094495,0.0,3.0,0.0,178.745714,201.31,15.405,65.235,17.805,...,0.0,0.0,57.0,1.0,0.0,3.0,1.0,3.0,156.0,0.0
3598,4190.0,25.528757,0.0,2.0,0.0,178.745714,201.31,15.405,65.235,17.805,...,1.0,5.0,56.0,0.0,0.0,5.0,0.0,2.0,175.0,0.0

In [65]:
c_train.isna().sum()

ID_C              0
BMI21             0
ETHANL24          0
CIGT21            0
CURSMK21          0
CARB              0
CHOL              0
DFIB              0
PROT              0
SFAT              0
TFAT              0
TCAL              0
HDLSIU21          0
LDLSIU22          0
TCHSIU21          0
TRGSIU21          0
SBPB15            0
SBPB16            0
ANTB04A           0
ANTB04B           0
CGMI24            0
APASIU21          0
APBSIU21          0
HYPTMD21          0
ANTICOAGCODE21    0
ASPIRINCODE21     0
STATINCODE21      0
HYPTMDC#N/AD21    0
HYPRT24           0
CIGTYR01          0
V2AG22            0
RACGRP            0
DIABTS22          0
LVL01             0
GENDER            0
CIGT21.1          0
ANTA01            0
CHOLMDCCODE21     0
dtype: int64

In [66]:
c_test.isna().sum()

ID_C              0
BMI21             0
ETHANL24          0
CIGT21            0
CURSMK21          0
CARB              0
CHOL              0
DFIB              0
PROT              0
SFAT              0
TFAT              0
TCAL              0
HDLSIU21          0
LDLSIU22          0
TCHSIU21          0
TRGSIU21          0
SBPB15            0
SBPB16            0
ANTB04A           0
ANTB04B           0
CGMI24            0
APASIU21          0
APBSIU21          0
HYPTMD21          0
ANTICOAGCODE21    0
ASPIRINCODE21     0
STATINCODE21      0
HYPTMDC#N/AD21    0
HYPRT24           0
CIGTYR01          0
V2AG22            0
RACGRP            0
DIABTS22          0
LVL01             0
GENDER            0
CIGT21.1          0
ANTA01            0
CHOLMDCCODE21     0
dtype: int64

In [67]:
import sklearn.linear_model as sk
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(C=1.0, penalty = 'l1', solver='liblinear',class_weight='balanced')
clf.fit(c_train,y_train)

LogisticRegression(class_weight='balanced', penalty='l1', solver='liblinear')

In [68]:
pred_visit_1 = clf.predict(c_test)
accuracy_score(pred_visit_1,y_test)

0.6647101980924431

In [69]:
roc_auc_score(y_test, pred_visit_1)

0.6541821898387788

In [70]:
confusion_matrix(y_test, pred_visit_1)

array([[1419,  688],
       [ 226,  393]], dtype=int64)