In [113]:
import pip
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score,roc_auc_score

In [2]:
import pandas as pd
import numpy as np
import pandas.testing as tm
import matplotlib.pyplot as plt

In [117]:
data=pd.read_csv(r'C:\Users\Student\Downloads\visit2_TotalOutcome (2)(2).csv')

In [118]:
np.random.seed(1024)

In [119]:
y=data.CLASS
x=data.drop("CLASS", axis = 1)
z=x.drop("MOVE", axis = 1)
a=z.drop("LIPA08", axis = 1)
b=a.drop("CHMA09", axis = 1)
c=b.drop("HMTA03", axis = 1)

In [120]:
c_train, c_test, y_train, y_test = train_test_split(c,y,test_size = 0.2)
ccols = c_train.columns
csols = c_test.columns

In [121]:
c_train.head()

,ID_C,BMI21,ETHANL24,CIGT21,CURSMK21,CARB,CHOL,DFIB,PROT,SFAT,...,HYPRT24,CIGTYR01,V2AG22,RACGRP,DIABTS22,LVL01,GENDER,CIGT21.1,ANTA01,CHOLMDCCODE21
3690,4300,47.992370,0.0,2,0,NaN,NaN,NaN,NaN,NaN,...,1,400,49,0,1,4,0,2,173.0,0
10828,12526,18.476762,0.0,3,0,NaN,NaN,NaN,NaN,NaN,...,0,0,58,0,0,4,1,3,163.0,0
6959,8098,34.102680,151.0,2,0,NaN,NaN,NaN,NaN,NaN,...,1,315,65,0,0,5,0,2,189.0,0
1182,1392,28.704297,0.0,1,1,NaN,NaN,NaN,NaN,NaN,...,0,2880,65,1,0,1,0,1,173.0,0
1958,2285,20.848519,0.0,3,0,296.41,322.5,31.94,81.18,37.18,...,1,0,68,0,0,1,0,3,169.0,0

In [122]:
from impyute.imputation.cs import mice

# start the MICE training
imputed_c_train=mice(c_train.values, m =5)

In [123]:
from impyute.imputation.cs import mice

# start the MICE training
imputed_c_test=mice(c_test.values, m = 5)

m = c_test.dtypes

In [124]:
m

ID_C                int64
BMI21             float64
ETHANL24          float64
CIGT21              int64
CURSMK21            int64
CARB              float64
CHOL              float64
DFIB              float64
PROT              float64
SFAT              float64
TFAT              float64
TCAL              float64
HDLSIU21          float64
LDLSIU22          float64
TCHSIU21          float64
TRGSIU21          float64
SBPB15            float64
SBPB16            float64
ANTB04A           float64
ANTB04B           float64
CGMI24              int64
APASIU21            int64
APBSIU21            int64
HYPTMD21            int64
ANTICOAGCODE21      int64
ASPIRINCODE21       int64
STATINCODE21        int64
HYPTMDC#N/AD21      int64
HYPRT24             int64
CIGTYR01            int64
V2AG22              int64
RACGRP              int64
DIABTS22            int64
LVL01               int64
GENDER              int64
CIGT21.1            int64
ANTA01            float64
CHOLMDCCODE21       int64
dtype: object

In [125]:
imputed_c_train = pd.DataFrame(imputed_c_train,columns=ccols)

In [126]:
imputed_c_train

,ID_C,BMI21,ETHANL24,CIGT21,CURSMK21,CARB,CHOL,DFIB,PROT,SFAT,...,HYPRT24,CIGTYR01,V2AG22,RACGRP,DIABTS22,LVL01,GENDER,CIGT21.1,ANTA01,CHOLMDCCODE21
0,4300.0,47.992370,0.0,2.0,0.0,194.810549,236.248593,20.076930,74.865530,19.965583,...,1.0,400.0,49.0,0.0,1.0,4.0,0.0,2.0,173.0,0.0
1,12526.0,18.476762,0.0,3.0,0.0,195.959058,220.926624,20.009493,74.171302,20.475821,...,0.0,0.0,58.0,0.0,0.0,4.0,1.0,3.0,163.0,0.0
2,8098.0,34.102680,151.0,2.0,0.0,192.345780,184.675231,14.517541,53.775340,18.759297,...,1.0,315.0,65.0,0.0,0.0,5.0,0.0,2.0,189.0,0.0
3,1392.0,28.704297,0.0,1.0,1.0,196.290143,273.409101,11.747738,65.175864,22.364301,...,0.0,2880.0,65.0,1.0,0.0,1.0,0.0,1.0,173.0,0.0
4,2285.0,20.848519,0.0,3.0,0.0,296.410000,322.500000,31.940000,81.180000,37.180000,...,1.0,0.0,68.0,0.0,0.0,1.0,0.0,3.0,169.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10895,702.0,28.727377,105.6,2.0,0.0,194.401152,181.871577,14.768024,57.668097,19.563101,...,0.0,620.0,59.0,0.0,0.0,3.0,0.0,2.0,177.0,0.0
10896,3100.0,26.723838,0.0,2.0,0.0,195.680933,214.477295,19.510497,75.426413,20.030637,...,1.0,960.0,53.0,0.0,0.0,3.0,0.0,2.0,174.0,1.0
10897,2959.0,20.918528,10.8,2.0,0.0,195.677642,188.941661,19.146009,74.061132,20.170573,...,0.0,100.0,49.0,0.0,0.0,5.0,1.0,2.0,170.0,0.0
10898,10563.0,32.596755,0.0,2.0,0.0,195.376268,231.484007,19.226137,75.139783,20.086355,...,1.0,120.0,51.0,0.0,0.0,5.0,1.0,2.0,167.0,0.0
10899,7071.0,36.784597,211.4,2.0,0.0,192.119789,142.843103,13.586140,44.897879,19.283528,...,0.0,880.0,65.0,0.0,0.0,4.0,1.0,2.0,166.0,0.0

In [127]:
imputed_c_train.isna().sum()

ID_C              0
BMI21             0
ETHANL24          0
CIGT21            0
CURSMK21          0
CARB              0
CHOL              0
DFIB              0
PROT              0
SFAT              0
TFAT              0
TCAL              0
HDLSIU21          0
LDLSIU22          0
TCHSIU21          0
TRGSIU21          0
SBPB15            0
SBPB16            0
ANTB04A           0
ANTB04B           0
CGMI24            0
APASIU21          0
APBSIU21          0
HYPTMD21          0
ANTICOAGCODE21    0
ASPIRINCODE21     0
STATINCODE21      0
HYPTMDC#N/AD21    0
HYPRT24           0
CIGTYR01          0
V2AG22            0
RACGRP            0
DIABTS22          0
LVL01             0
GENDER            0
CIGT21.1          0
ANTA01            0
CHOLMDCCODE21     0
dtype: int64

In [129]:
import sklearn.linear_model as sk
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(C=1.0, penalty = 'l1', solver='liblinear',class_weight='balanced').fit(imputed_c_train,y_train)
pred_visit_2 = clf.predict(c_test)
accuracy_score(pred_visit_2,y_test)

C:\Users\Student\anaconda3\lib\site-packages\sklearn\svm\_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [130]:
imputed_c_test = pd.DataFrame(imputed_c_test,columns=ccols)
imputed_c_test

,ID_C,BMI21,ETHANL24,CIGT21,CURSMK21,CARB,CHOL,DFIB,PROT,SFAT,...,HYPRT24,CIGTYR01,V2AG22,RACGRP,DIABTS22,LVL01,GENDER,CIGT21.1,ANTA01,CHOLMDCCODE21
0,6344.0,22.021815,39.6,2.0,0.0,190.572488,275.724174,19.001451,66.801558,21.017657,...,1.0,270.0,58.0,0.0,1.0,3.0,0.0,2.0,173.0,0.0
1,5010.0,35.037379,0.0,2.0,0.0,189.837877,208.313446,13.202929,67.231959,19.644002,...,1.0,0.0,66.0,1.0,0.0,2.0,1.0,2.0,157.0,0.0
2,3158.0,33.558239,0.0,3.0,0.0,189.982512,186.150976,12.572485,66.766160,21.059734,...,0.0,0.0,54.0,0.0,0.0,5.0,1.0,3.0,160.0,0.0
3,9154.0,37.160301,422.4,1.0,1.0,190.226389,244.283755,11.411127,67.081551,20.014743,...,0.0,108.0,48.0,1.0,0.0,6.0,1.0,1.0,167.0,0.0
4,106.0,31.072443,10.8,3.0,0.0,189.604181,219.437297,20.604974,69.932827,19.768345,...,0.0,0.0,51.0,0.0,0.0,4.0,1.0,3.0,160.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2721,1191.0,23.161750,0.0,2.0,0.0,191.096788,211.773040,15.362612,62.962370,21.064042,...,0.0,525.0,63.0,0.0,0.0,3.0,1.0,2.0,171.0,0.0
2722,8766.0,27.458256,223.2,1.0,1.0,191.205158,293.148739,15.739229,63.151742,20.716982,...,0.0,640.0,47.0,1.0,0.0,2.0,0.0,1.0,175.0,0.0
2723,13265.0,27.681661,407.0,2.0,0.0,189.652456,232.716055,15.255072,65.130739,19.700660,...,0.0,620.0,59.0,0.0,0.0,5.0,0.0,2.0,170.0,0.0
2724,4313.0,24.094495,0.0,3.0,0.0,190.251949,262.537605,19.955092,66.804649,18.764566,...,0.0,0.0,57.0,1.0,0.0,3.0,1.0,3.0,156.0,0.0
2725,4190.0,25.528757,0.0,2.0,0.0,190.309211,204.693969,16.780410,67.776784,18.481758,...,1.0,5.0,56.0,0.0,0.0,5.0,0.0,2.0,175.0,0.0

In [131]:
imputed_c_test.isna().sum()

ID_C              0
BMI21             0
ETHANL24          0
CIGT21            0
CURSMK21          0
CARB              0
CHOL              0
DFIB              0
PROT              0
SFAT              0
TFAT              0
TCAL              0
HDLSIU21          0
LDLSIU22          0
TCHSIU21          0
TRGSIU21          0
SBPB15            0
SBPB16            0
ANTB04A           0
ANTB04B           0
CGMI24            0
APASIU21          0
APBSIU21          0
HYPTMD21          0
ANTICOAGCODE21    0
ASPIRINCODE21     0
STATINCODE21      0
HYPTMDC#N/AD21    0
HYPRT24           0
CIGTYR01          0
V2AG22            0
RACGRP            0
DIABTS22          0
LVL01             0
GENDER            0
CIGT21.1          0
ANTA01            0
CHOLMDCCODE21     0
dtype: int64

In [132]:
import sklearn.linear_model as sk
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(C=1.0, penalty = 'l1', solver='liblinear',class_weight='balanced')
clf.fit(imputed_c_train,y_train)

C:\Users\Student\anaconda3\lib\site-packages\sklearn\svm\_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "

LogisticRegression(class_weight='balanced', penalty='l1', solver='liblinear')

In [133]:
imputed_c_test.nunique

<bound method DataFrame.nunique of          ID_C      BMI21  ETHANL24  CIGT21  CURSMK21        CARB        CHOL  \
0      6344.0  22.021815      39.6     2.0       0.0  190.572488  275.724174
1      5010.0  35.037379       0.0     2.0       0.0  189.837877  208.313446
2      3158.0  33.558239       0.0     3.0       0.0  189.982512  186.150976
3      9154.0  37.160301     422.4     1.0       1.0  190.226389  244.283755
4       106.0  31.072443      10.8     3.0       0.0  189.604181  219.437297
...       ...        ...       ...     ...       ...         ...         ...
2721   1191.0  23.161750       0.0     2.0       0.0  191.096788  211.773040
2722   8766.0  27.458256     223.2     1.0       1.0  191.205158  293.148739
2723  13265.0  27.681661     407.0     2.0       0.0  189.652456  232.716055
2724   4313.0  24.094495       0.0     3.0       0.0  190.251949  262.537605
2725   4190.0  25.528757       0.0     2.0       0.0  190.309211  204.693969

           DFIB       PROT       SFAT  ...  HYPRT24  CIGTYR01  V2AG22  RACGRP  \
0     19.001451  66.801558  21.017657  ...      1.0     270.0    58.0     0.0
1     13.202929  67.231959  19.644002  ...      1.0       0.0    66.0     1.0
2     12.572485  66.766160  21.059734  ...      0.0       0.0    54.0     0.0
3     11.411127  67.081551  20.014743  ...      0.0     108.0    48.0     1.0
4     20.604974  69.932827  19.768345  ...      0.0       0.0    51.0     0.0
...         ...        ...        ...  ...      ...       ...     ...     ...
2721  15.362612  62.962370  21.064042  ...      0.0     525.0    63.0     0.0
2722  15.739229  63.151742  20.716982  ...      0.0     640.0    47.0     1.0
2723  15.255072  65.130739  19.700660  ...      0.0     620.0    59.0     0.0
2724  19.955092  66.804649  18.764566  ...      0.0       0.0    57.0     1.0
2725  16.780410  67.776784  18.481758  ...      1.0       5.0    56.0     0.0

      DIABTS22  LVL01  GENDER  CIGT21.1  ANTA01  CHOLMDCCODE21
0          1.0    3.0     0.0       2.0   173.0            0.0
1          0.0    2.0     1.0       2.0   157.0            0.0
2          0.0    5.0     1.0       3.0   160.0            0.0
3          0.0    6.0     1.0       1.0   167.0            0.0
4          0.0    4.0     1.0       3.0   160.0            0.0
...        ...    ...     ...       ...     ...            ...
2721       0.0    3.0     1.0       2.0   171.0            0.0
2722       0.0    2.0     0.0       1.0   175.0            0.0
2723       0.0    5.0     0.0       2.0   170.0            0.0
2724       0.0    3.0     1.0       3.0   156.0            0.0
2725       0.0    5.0     0.0       2.0   175.0            0.0

[2726 rows x 38 columns]>

In [134]:
imputed_c_train.nunique()

ID_C              10900
BMI21              4184
ETHANL24            607
CIGT21                4
CURSMK21              2
CARB              10894
CHOL              10895
DFIB              10775
PROT              10873
SFAT              10801
TFAT              10864
TCAL              10896
HDLSIU21            125
LDLSIU22           1011
TCHSIU21            284
TRGSIU21            500
SBPB15               81
SBPB16               53
ANTB04A             121
ANTB04B             111
CGMI24                2
APASIU21            218
APBSIU21            207
HYPTMD21              2
ANTICOAGCODE21        2
ASPIRINCODE21         2
STATINCODE21          2
HYPTMDC#N/AD21        2
HYPRT24               2
CIGTYR01            490
V2AG22               25
RACGRP                2
DIABTS22              2
LVL01                 7
GENDER                2
CIGT21.1              4
ANTA01               66
CHOLMDCCODE21         2
dtype: int64

In [139]:
pred_visit_2 = clf.predict(imputed_c_test)
accuracy_score(pred_visit_2,y_test)

0.6669112252384446

In [137]:
roc_auc_score(y_test, pred_visit_2)

0.6561764654015041